twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - '@TetranzSelect2Entity/Form/fields.html.twig'
        - bootstrap_4_horizontal_layout.html.twig
        - bootstrap_4_layout.html.twig
        # https://github.com/ttskch/select2-bootstrap4-theme ??